### ISSUE TITLE
Crash in Windows due to access to `appWindow` attribute of a `NWWindow` object in `nw-winstate.js`

### ISSUE THREAD

**Issue by sadra-barikbin** [mauvilsa/nw-page-editor#10]
Hi there!
Thank you @mauvilsa for creating this repo.

I encounter app crash while running it on Windows 10, albeit it successfully runs on Ubuntu 22.04. I delved into the problem using chrome devtools by manually adding `win.showDevTools()` to `nw-app.js`'s `$(windows).load`. It turned out that the following causes the app to crash:
![Capture](https://github.com/mauvilsa/nw-page-editor/assets/22097587/d43f8e57-91be-4448-a81e-a0c428a2038c)

I couldn't find out why the same code didn't cause failure in Linux.

Anyway by replacing `appWindow` usages, that were done in order to get window bounds, with direct access to proper attributes of `win` object, the problem disappeared:
```js
// In `nw-app.js`:
var b = win.appWindow.getBounds();
nw.Window.open('../html/index.html#'+global.pageNum,{"width":b.width,"height":b.height});
// To
nw.Window.open('../html/index.html#'+global.pageNum,{"width":win.width,"height":win.height});

// In `nw-winstate.js`:
winState.x = win.appWindow.outerBounds.left;
winState.y = win.appWindow.outerBounds.top;
winState.width = win.appWindow.outerBounds.width;
winState.height = win.appWindow.outerBounds.height;
// To
winState.x = win.x;
winState.y = win.y;
winState.width = win.width;
winState.height = win.height;
```

Possibly related issue in NW.js:
https://github.com/nwjs/nw.js/issues/7262#issuecomment-564017904

On both Ubuntu 22.04 & Windows 10 systems, I used the last version of NWjs (0.83) and also the latest commit of this repo.

**Comment by mauvilsa** [comment]
Thank you for reporting! Please, go ahead and create a pull request.
