### ISSUE TITLE
Validation error on store

### ISSUE THREAD

**Issue by dasch124** [mauvilsa/nw-page-editor#4]
We have installed the docker image mauvilsa/nw-page-editor-web:2019.01.28 from dockerhub (the latest image did not work), however when I try to edit a text box in the sample file at {ourmachine}/app/?f=lorem.xml&n=1 I receive the following validation error on saving:

~~~
Problems saving file ../data/lorem.xml: 400: Page XML schema validation failed:
../data/lorem.xml~2:85: element Group: Schemas validity error : Element '{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}Group': This element is not expected. Expected is ( {http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}Page ).
../data/lorem.xml~2 fails to validate
SvgCanvas/self.throwError@https://page-editor.acdh-dev.oeaw.ac.at/js/svg-canvas.js?v=2019.01.28:248:15
saveFile/<@https://page-editor.acdh-dev.oeaw.ac.at/js/web-app.js?v=2019.01.28:176:24
i@https://page-editor.acdh-dev.oeaw.ac.at/js/jquery-3.2.1.min.js:2:28017
fireWith@https://page-editor.acdh-dev.oeaw.ac.at/js/jquery-3.2.1.min.js:2:28783
A@https://page-editor.acdh-dev.oeaw.ac.at/js/jquery-3.2.1.min.js:4:14035
c/<@https://page-editor.acdh-dev.oeaw.ac.at/js/jquery-3.2.1.min.js:4:16323
~~~

Anything we can do about it?

**Comment by mauvilsa** [comment]
@dasch124 the web version has not been used much so when the desktop version changes, the web one can break without anyone noticing for some time. Though since both versions share almost all the code fixing it tends to be easy. Please try again with the new version mauvilsa/nw-page-editor-web:2020.03.03. Hopefully it should work now.

**Comment by dasch124** [comment]
Hi @mauvilsa great, thank you for the quick fix, we'll give it a try and report back!

**Comment by dasch124** [comment]
Hi, validation seems to succeed now, however now there’s another error:

> Problems saving file ../data/lorem.xml: 400: Problems writing to temporal file
SvgCanvas/self.throwError@https://{hostname}/js/svg-canvas.js?v=2020.03.03:250:15
saveFile/<@https://{hostname}/js/web-app.js?v=2020.03.03:178:24
i@https://{hostname}/js/jquery-3.2.1.min.js:2:28017
fireWith@https://{hostname}/js/jquery-3.2.1.min.js:2:28783
A@https://{hostname}/js/jquery-3.2.1.min.js:4:14035
c/<@https://{hostname}/js/jquery-3.2.1.min.js:4:16323

**Comment by mauvilsa** [comment]
You did not give any details of exactly what you have been doing to be able to reproduce the problem. Though, doing a few tests for some reason I decided to test it in Firefox and I do get that same error message. Don't know if this is your case. But anyway only use this with Chrome or Chromium or any other derivative. Support for Firefox probably will not be fixed any time soon.

**Comment by dasch124** [comment]
Hi, thank you for your reply! Yes, I was checking it out on Firefox. I didn’t expect a browser-specific problem, so being in a hurry it didn’t cross my mind to provide you with this information, sorry for having been so brief! Anyway, I can confirm that the error does not occur with Chromium, so I’m perfectly happy with using that!
