### ISSUE TITLE
Add short-cut to go to single-page view in one go (without using the current zoom option).

### ISSUE THREAD

**Issue by didirus** [mauvilsa/nw-page-editor#7]
Viewing the separate pages of a multi-page document, is very slow on my computer. Could a short-cut be implemented, other than [ ctr/cmd +plus/minus / shift + mouse wheel ], to speed up the single-page view?

**Comment by mauvilsa** [comment]
This is a good idea. I have just pushed a commit which adds this feature. There are two new keyboard shortcuts: ctrl/cmd+1 (zoom to page) and ctrl/cmd+2 (zoom to element). When an element is selected these will zoom into the page/element selected. If nothing is selected, it zooms into the page/element pointed by the mouse cursor.
